### ISSUE TITLE
Untagged maritime boundaries

### ISSUE THREAD

**Issue by mojodna** [stamen/pinterest.tm2#12]
Offshore boundaries aren't tagged with `maritime=yes`:

![image](https://cloud.githubusercontent.com/assets/45/2756553/92059ea2-c978-11e3-822a-eeed6bbd805e.png)

- [x] Baja California
- [x] Georgia
- [x] Nova Scotia / New Brunswick
- [x] Cuba
- [ ] Japan
- [ ] Shanghai

/cc @myamartino

**Comment by sethfitz** [comment]
No longer relevant.
